### PR TITLE
[AAAAAAAAAAAAA] [PORT] Ports 3 Months of Various Organ and Species Related Fixes and QoL Changes

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

FUCK, I NEED MOST OF THIS, SHIT.
Anyways.

Ports 59 PRs from TG.

## How Does This Help ***Gameplay***?

Game less fuck.

## How Does This Help ***Roleplay***?

Less fuck game.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

image
image

</details>

## Changelog

:cl:
code: 3 months of species and organ fixes. Code less fuck.
qol: Machines now have interact particles.
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
This will fail CI in at least two different ways right now, I am very aware, don't review this yet. Also not done.

**Comment by LemonInTheDark** [comment]
Hello bestie

**Comment by RimiNosha** [comment]
Hey lemon!

**Comment by RimiNosha** [comment]
No runtimes on my local, fingers crossed.

**Comment by RimiNosha** [comment]
IT FUCKING WORKS

**Comment by QuacksQ** [comment]
Insanely based pr

**Comment by RimiNosha** [comment]
Updated with a couple of screens, but frankly, CI passing is like 90% of this, cause this is all tested via CI.

**Review by nevimer — APPROVED** [review]
Full send.

**Pull request merged**
