### PR TITLE
Kilo virology removal, chem factory removal, chem storage addition

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Adds an unnecessarily big chem storage room where virology was because my map editing is rusty as hell and the kilo decal spam makes me unhappy.
Removes the chem factory room since plumbing has been removed and that room isn't usable for that anymore. It's just a big empty maintenance room without any lights or air pipes. Enjoy the free DIY stripper bar or whatever you turn that into. 
Made the "cargo warehouse" north of the station have an overmap preset docking port instead of the whiteship one it had. 
Also added a room to plop cryo into in dorms.

## How Does This Help ***Gameplay***?
It in fact has nothing to do with gameplay.

## How Does This Help ***Roleplay***?
Big empty space in maintenance for building quirky things. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

I tested it but forgot to take pictures. I'll get to it later.
</details>

## Changelog

:cl:
del: Removed Kilo Virology
add: Added chem storage in the space virology took up.
del: Removed Kilo Chem Factory
add: Added a suspiciously chem factory shaped empty room where a chem factory room used to be.
add: Empty room for cryo in dorms
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Diff:
image
New:
image

**Review by RimiNosha — CHANGES_REQUESTED** [review]
The maintenance room still has medical access requirements. Please change that to either be nothing, or normal maintenance access.

**Comment by QuacksQ** [comment]
@GuiltyNeko This PR might have caused Hardsuits to not be present on the map anymore during the playtest, can you make sure that all the Suit storage units are their Hardsuit subtype? (I replaced them all in #234)

**Review by RimiNosha — CHANGES_REQUESTED** [review]
Talked about in discord, but putting here for posterity:

Add some decals and clutter (doesn't need to be a lot), cause those new rooms are strangely clean compared to literally anywhere else on the station.

Potentially put a wall in on the right and make that little section it's own room, though not a must-do.

**Review by RimiNosha — APPROVED** [review]
Merging for now, I'll make my own edits later.

**Pull request merged**
