### PR TITLE
[Removal] Murders FOV from the game

### PR DESCRIPTION
**Pull request by QuacksQ**
## About The Pull Request
Removes FOV from the game, This was a Skyrat feature at first that eventually got added on TG because oranges liked it. I am not oranges and I severly dislike FOV, having people or mobs pop out of existance when you wear certain clothing or because the game bugged out and decided that you cant see someone is horrible and I hate it so much. (Yes this is a rage PR)

This undoes the mistakes from this PR: 
- https://github.com/tgstation/tgstation/pull/63312

This also qualifies as a port of this:
- https://github.com/DaedalusDock/daedalusdock/pull/209

Ty @Kapu1178  for linking your PR ❤️ 

### Please for the love of god make this stop
https://user-images.githubusercontent.com/79924768/235373020-6426027c-294c-4479-917a-bac343d8d0a5.mp4

## How Does This Help ***Gameplay***?
No more FOV hiding things from your screen while you should just be able to see them. Clothing (Mainly masks or hoods) will not affect your FOV or vision cone either so thats nice, smoother and better gaming overall so big QOL change :)

## How Does This Help ***Roleplay***?
Minimal impact on roleplay.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary> 

https://user-images.githubusercontent.com/79924768/235373239-e8ae27a0-8f6b-4430-b651-cd4536e06591.mp4

### Effects for the blind.
https://user-images.githubusercontent.com/79924768/235457356-2912d7d1-0d8d-42ff-8d26-dfc32216d147.mp4

</details>

## Changelog
:cl:
qol: FOV no longer exists and will be unable to hinder people in their gaming.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
GAME_PLANE_UPPER is part of FOV

**Comment by QuacksQ** [comment]
> GAME_PLANE_UPPER is part of FOV
> 
>     * [Removes Field of View and returns everything to the GAME_PLANE DaedalusDock/daedalusdock#209](https://github.com/DaedalusDock/daedalusdock/pull/209)

Yooo thanks for pointing this out dude 🙌 😄

**Review by RimiNosha — APPROVED** [review]
Damn, that's a lot of extra var defs. Glad we don't need to worry about these anymore.

Also thanks for taking the time to keep the blind effects, it's the one solace in the hell that is the black void for blind characters.

**Comment by nevimer** [comment]
Ready for merge? I will test before merging when indicated.

**Comment by QuacksQ** [comment]
> Ready for merge? I will test before merging when indicated.

I've made the changes I wanted to make and its ready to merge on my end yeah.

**Pull request merged**
