### PR TITLE
Space Audio Stuff!

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request
Idea and code stolen from: https://github.com/DaedalusDock/daedalusdock/pull/523

I was reminded that space is like- entirely quiet. Let's add some background audio!

Adds:
 - A breathing sound when in space.
   - I'll make this a little more advanced when I'm not speedrunning this in like 10 minutes flat, and have it so it's when you have internals on full stop.
 - The radio receive sound is played when you're wearing a spacesuit helmet (or similar) when someone speaks next to you.
   - Maybe I'll make speech pressure-based? Depends on if it'd be fun and perf-friendly.

Breathing sound: https://freesound.org/people/univ_lyon3/sounds/324562/

## How Does This Help ***Gameplay***?

Immersion, and also gives you a bit more warning before you start gasping, cause you suddenly stop breathing!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

https://github.com/Artea-Station/Artea-Station-Server/assets/106692773/d82fb40a-8613-4b48-8095-4ad9475861c6

</details>

## Changelog

:cl: Kapu (Original), RimiNosha (Port)
add: Breathing sounds when internals are on in space.
add: Mock spacesuit intercom sounds, very basic implementation for now.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
credit please, this is my code.

You want to directly send the sound instead of using playsound() because

1. Playsound() sends to all nearby people, which doesnt really make sense in this context
2. Playsound() and playsound_local() take into account sound environment, which doesnt make sense in this context.

**Comment by RimiNosha** [comment]
Wack, I thought I pasted a link.

On your other point:
Playsound respects atmospherics, and (to me at least), being able to hear the *very* quiet breathing while in a pressurized environment would be neat.

Though for the fake radio sound, yeah, that should've been local.

**Comment by Kapu1178** [comment]
> Wack, I thought I pasted a link.
> 
> On your other point: Playsound respects atmospherics, and (to me at least), being able to hear the _very_ quiet breathing while in a pressurized environment would be neat.
> 
> Though for the fake radio sound, yeah, that should've been local.

Things like echo and reverberation are applied, and the intent of the effect is that you are hearing it reverberate through your skull, not actually hearing from a room.

**Comment by RimiNosha** [comment]
I hate audio code.

**Pull request merged**
