### PR TITLE
[PORT] Various Atmos/Turf Fixes and Optimisations, Plus Lazyloading!

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

Ports:
- https://github.com/tgstation/tgstation/pull/70729
- https://github.com/tgstation/tgstation/pull/71785
- https://github.com/tgstation/tgstation/pull/71818
- https://github.com/tgstation/tgstation/pull/72339
- https://github.com/tgstation/tgstation/pull/72800
- https://github.com/tgstation/tgstation/pull/73261
- https://github.com/tgstation/tgstation/pull/70965
- https://github.com/tgstation/tgstation/pull/71295
- https://github.com/tgstation/tgstation/pull/70966

Good things to have, also makes it possible to have smaller maps centered, drastically saving on load times for mapping programs.

## Proof of Testing

Hard to exhaustively test, so it's gonna be a case of ensuring some of our previous errors are gone.

To be tested locally, mostly waiting on CI to catch any mapping issues for me first.

## Changelog

:cl:
admin: Admins now have a lazy-load template command.
code: Performance and server stability should be marginally better.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
Need to run the updatemaps scripts, I think

**Comment by RimiNosha** [comment]
Yea, I'm gonna have to stare hard at this one when I don't have more pressing matters.

**Comment by nevimer** [comment]
Merging once conflicts are resolved. I'll do a pass too.

**Comment by RimiNosha** [comment]
Tested, shuttles worked fine, and atmos behaved as expected. Lazyload templates also worked perfectly.

**Comment by RimiNosha** [comment]
I LITERALLY CAN'T REPLICATE THIS LOCALLY YOU LITTLE SHIT

**Comment by RimiNosha** [comment]
Broken by ZAS, horrifically outdated, and daedalus has already done the important parts of this, so we can just steal that should motivation be found for centered maps.

**Pull request closed without merging**
