### PR TITLE
[PORT] ZAS, Explosive Decompression [MDB IGNORE]

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

Stolen from DD:
- https://github.com/DaedalusDock/daedalusdock/pull/378
- https://github.com/DaedalusDock/daedalusdock/pull/328
- https://github.com/DaedalusDock/daedalusdock/pull/197
- https://github.com/DaedalusDock/daedalusdock/pull/102
- https://github.com/DaedalusDock/daedalusdock/pull/87
- https://github.com/DaedalusDock/daedalusdock/pull/77
- https://github.com/DaedalusDock/daedalusdock/pull/70
- https://github.com/DaedalusDock/daedalusdock/pull/45
- https://github.com/DaedalusDock/daedalusdock/pull/34
- https://github.com/DaedalusDock/daedalusdock/pull/23
- https://github.com/DaedalusDock/daedalusdock/pull/5
- https://github.com/DaedalusDock/daedalusdock/pull/1
- And more I've probably included as a byproduct of resetting files to DD.

Anyways, see title, I'm posting this early cause there's harddels that I need to track down, and I don't have the patience to leave a server open in the background for possibly around an hour.

Near future TODOs:
- Add a new type of generator, potentially the [RBMK](https://nsv.beestation13.com/wiki/Guide_to_the_Nuclear_Reactor).
- Fix up and readd bay's version of the R-UST.
- Add a new pipeline for heat waste to space radiators. This should make heat management more of an active thing rather than making it yet another "add more power lol" thing.
  - Yeah, there's gonna have to be a doc on this so I get it right 😔 
- Add more gasses, potentially look into adding new ways of making gasses.
- Implement evil plasma mechanics properly. They're disabled right now to avoid ballooning my fucking changelog size and the amount of mechanics added in one PR.

## How Does This Help ***Gameplay***?

Space is dangerous as fuck now, and you shouldn't be careless when changing the station.

## How Does This Help ***Roleplay***?

"Hey, are you gonna patch that hole?"
"Nah, SSair is running at 2500% tidi, we've hours before it becomes a problem. Just stick a space heater inside for the lizards."

## Proof of Testing

In your wildest dreams. This will be buggy while I iron out all the issues found in playtests.

## Changelog

:cl: Kapu (original), RimiNosha (port)
add: ZAS, a blazing fast, if somewhat simplified atmos system.
del: LINDA (our old, slow as balls atmos system)
add: Explosive decompression, which is, as the name suggests, dangerous.
balance: Space is no longer magically ultra-cold for pipes.
qol: Air alarms now have inbuilt heaters. They're nowhere near as powerful as space heaters, though!
del: Aninoblium, Hypernoblium, Freon, Halon, Healium, Pluoxium, Nitrium, BZ, Masma, Proto Nitrate, Zauker.
spellcheck: Water Vapour > Steam
add: Alium, a fucked gas that will have random attributes each round.
add: Deuterium, which burns ~20% hotter than hydrogen.
add: Argon, Neon, Krypton, Xenon, Boron, which are all noble gases with differing behaviours.
add: Methane, which is stinky, as is the replacement for Miasma.
add: Ammonia, Chlorine, Methyl Bromide, Nitrogen Dioxide, all of which are potent toxins.
add: Nitric Oxide, Sulfur Dioxide.
add: Walls can now melt from high temperatures.
del: Openturf fusion. Replacement coming in the near future.
del: HFR. Not like many folk knew the thing even existed, nevermind how it works.
del: Pressure resistance. Anything not anchored will be moved by pressure effects.
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Why the fuck is it only pre-placed monkeys fucking everything?

Also why only specifically those three? The fuck?

**Comment by RimiNosha** [comment]
Turbines confirmed working with relatively balanced values. May need adjustments if power is found to be too much, or too little.

**Comment by ReturnToZender** [comment]
Kicking absolute ass Rimi, keep up the good work 👍

**Comment by RimiNosha** [comment]
Tempted to YOLO merge this so I can work on the near-future TODO stuff immediately.

**Comment by RimiNosha** [comment]
> Kicking absolute ass Rimi, keep up the good work 👍

Downstream Artea 😛

**Comment by RimiNosha** [comment]
Fuck it, YOLO

**Pull request merged**
