### PR TITLE
[PORT] Extreme Pressures Damage Buffening

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

https://github.com/DaedalusDock/daedalusdock/pull/521

This PR does a few things:
- It gets rid of some bullshit snowflake shitcode for hulk pressure damage.
- It DOUBLES maximum pressure damage. You won't notice this almost at all if you're spaced, as the cold will almost always kill first, but high pressure damage now **actually** does something.

## How Does This Help ***Gameplay***?

Makes coffee spacing a **really** bad idea now. This is a good thing. I'll eventually sort out firesuit behaviours.

## How Does This Help ***Roleplay***?

Coffee is not hot enough to allow you to space walk for minutes at a time, realistically.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

image

</details>

## Changelog

:cl:
code: Hulks now take burn damage from pressure. Not that anyone outside of admins would be able to notice.
balance: Extreme pressures damage your eyes and ears, and also hurts just a little more. Better bring a space suit!
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
The referenced PR was balanced for Brainmed where low damage automatically heals.

**Comment by RimiNosha** [comment]
Noted, though in the current code, it's fairly trivial to heal this damage by just eating any food, provided you didn't actually go into crit. If you did, then uh, yea, you'll need more than food and basic medkits.

**Comment by RimiNosha** [comment]
Drafted due to a lack of synth healing options.

**Comment by RimiNosha** [comment]
These changes seemed fine during playtests, merging cause I don't want to juggle merge conflicts with ZAS

**Pull request merged**
