### PR TITLE
[PORT] Moves us to 515, probably... (I dont know what I'm doing)

### PR DESCRIPTION
**Pull request by QuacksQ**
## About The Pull Request
Moves us to 515, Probably? I honestly dont know what I'm doing and I'm in over my head on this one so I'm just praying it works.

Ports the following from TG:
- https://github.com/tgstation/tgstation/pull/72033
- https://github.com/tgstation/tgstation/pull/72401
- https://github.com/tgstation/tgstation/pull/72657
- https://github.com/tgstation/tgstation/pull/73788
- https://github.com/tgstation/tgstation/pull/74380
## How Does This Help ***Gameplay***?
tiny Preformance increases so slightly smoother gaming.

## How Does This Help ***Roleplay***?
Minimal impact on roleplay.

## Proof of Testing

I really dont know how to test this so just trust me and CI.

image
## Changelog

:cl:
code: Moves us to completely to 515.
/:cl:

### CODE REVIEW

**Review by RimiNosha — CHANGES_REQUESTED** [review]
Uncomment this line

https://github.com/Artea-Station/Artea-Station-Server/blob/bb332f4eaa7378988778c2c63bed6206445a70c5/.github/alternate_byond_versions.txt#L9

And port this one while you're at it, cause it's somewhat relevant to the 515 tests https://github.com/tgstation/tgstation/pull/74380

**Comment by RimiNosha** [comment]
https://github.com/Artea-Station/Artea-Station-Server/blob/d02fb03e5d8a1d99fa34b28c95b2bbc779c23a0e/code/__byond_version_compat.dm#L23-L29

Yeet these lines please.

**Comment by QuacksQ** [comment]
> https://github.com/Artea-Station/Artea-Station-Server/blob/d02fb03e5d8a1d99fa34b28c95b2bbc779c23a0e/code/__byond_version_compat.dm#L23-L29
> 
> Yeet these lines please.

Done.

**Comment by QuacksQ** [comment]
image

what

**Review by RimiNosha — COMMENTED** [review]
https://github.com/QuacksQ/Artea-Station-Server/blob/515/code/__DEFINES/rust_g.dm

The calls in this file should be using the `LIBCALL` macro.

**Comment by RimiNosha** [comment]
Ah fuck, that's a lot of harddels in 515.

**Pull request closed without merging**
