### PR TITLE
[SUFFERING] Extra Customization! [IDB IGNORE]

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

Ports virtually every non-tesh/vox tail, hairstyle, horn, and ears.

Rewrites part of the rendering code for sprite overlays.

Features:
- Dynamically resizing colour pickers, no more extra colour options that do anything that other codebases suffer from!
- Previews for every single option!
- Easy to expand!
- Days of my time, and mountains of sanity lost!
- Many fixed mini-bugs, plus one big bug where synths couldn't pick their brain!

## How Does This Help ***Roleplay***?

You can represent your character far more accurately!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

image
image
image
image
image
image
image
image
image
image
image

</details>

## Changelog

:cl:
add: A metric fuckton of new customization stuff has been added!
qol: Humans and synths now have access to horns as customization options.
qol: Sprite colouring in the prefs menu is now far more obvious. Hair gradients are the most notable ones.
fix: Fixed facial hair gradient colour not showing in prefs.
fix: Fixed synth brain settings not showing.
code: Added a dynamically scaling (up to three choices) colour input!
refactor: Overhauled how sprite accessories are rendered, they now support multiple layers and colours!
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Should be ready.

**Comment by nevimer** [comment]
Quick Issue Testing: 
Unavailable to Synths:
- Snouts (synth snouts exist if you switch to lizard first), Frills, Body Markings (synth markings)
- All but the IPC Antenna's do not show up when selected on your character, but the sprites exist.

Working: 
- Drops parts when switching species properly. Woo! 
- Everything else, it seems. I must make more characters, to test.

**Comment by RimiNosha** [comment]
Fuck

**Comment by nevimer** [comment]
Ready for a review again?

**Comment by nevimer** [comment]
Passes CI, merging.

**Pull request merged**
