### PR TITLE
Added sounds to Security jackboots.

### PR DESCRIPTION
**Pull request by QuacksQ**
## About The Pull Request
Adds sounds to Security Jackboots! (Normal jackboots are unaffected by this and dont make sound)
Why? Because I simply think that its a funny feature that we could have. Plus if security marches down to somewhere to arrest a random tider you can hear them coming similar to how you can hear clowns from the sound of their shoes.
(I used some code from the clown shoes to do this because sec are also clowns) 

## How Does This Help ***Gameplay***?
It just does... Trust me on this one...

## How Does This Help ***Roleplay***?
Minimal impact on Roleplay.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary> 

https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/60f32a07-a4d1-41c5-8dd2-b65b7bb6213a

</details>

## Changelog
:cl:
soundadd: Security Jackboot now make sound when you walk around with them!
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
unsure about licensing as it is a hl2 sound

**Comment by RimiNosha** [comment]
https://www.reddit.com/r/valve/comments/mmxcm0/how_the_rights_to_valve_audio_work/

Due to there being no concrete licensing we can reference from an official source, though, I'd recommend picking out different sounds.

**Comment by QuacksQ** [comment]
> 

Any sources you recommend for finding free audio?

**Comment by RimiNosha** [comment]
Freesound.org is good, so long as you pay attention to the licenses. More or less anything CC is fine (with a couple of exceptions), so long as you note it down in the PR, and additionally in a text file, if it's BY.

**Review by RimiNosha — APPROVED** [review]
Yea, this is good to go once it passes CI. As funny as stealth sec is, with our planned maps, and already small size making antagonizing harder, let's give antags a leg up for default-footwear seccies.

**Pull request merged**
