### PR TITLE
[PAIN] [PORT] Modernizes our PDA code and brings it up to date with TG

### PR DESCRIPTION
**Pull request by QuacksQ**
## About The Pull Request
This PR ports the following from TG:
- https://github.com/tgstation/tgstation/pull/68251 
- https://github.com/tgstation/tgstation/pull/70291 
- https://github.com/tgstation/tgstation/pull/70319 
- https://github.com/tgstation/tgstation/pull/70344
- https://github.com/tgstation/tgstation/pull/70368
- https://github.com/tgstation/tgstation/pull/70485
- https://github.com/tgstation/tgstation/pull/70555 
- https://github.com/tgstation/tgstation/pull/70678 
- https://github.com/tgstation/tgstation/pull/70854 
- https://github.com/tgstation/tgstation/pull/71035 
- https://github.com/tgstation/tgstation/pull/71078
- https://github.com/tgstation/tgstation/pull/71317
- https://github.com/tgstation/tgstation/pull/71320
- https://github.com/tgstation/tgstation/pull/71602
- https://github.com/tgstation/tgstation/pull/71738
- https://github.com/tgstation/tgstation/pull/71467 
- https://github.com/tgstation/tgstation/pull/71507
- https://github.com/tgstation/tgstation/pull/71528
- https://github.com/tgstation/tgstation/pull/71732
- https://github.com/tgstation/tgstation/pull/72285
- https://github.com/tgstation/tgstation/pull/73070
- https://github.com/tgstation/tgstation/pull/73173
- https://github.com/tgstation/tgstation/pull/73500
- https://github.com/tgstation/tgstation/pull/73635 

As appearent from the **massive** list of prs from TG. This PR modernizes our PDA and modular computer code to be up to date with what TG has. A large amount of fixes, refactors and other changes are included and I recommend checking the list of Prs for more details on individual changes per PR.
## How Does This Help ***Gameplay***?
Minimal impact on gameplay aside from some stuff happening on the PDA side of things. Changes are mainly in the UI and code side of things but it still functions as it should and like old.

## How Does This Help ***Roleplay***?
Minimal impact on roleplay.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

### It just works
image

https://user-images.githubusercontent.com/79924768/229583155-f227bd8d-c0e9-4aac-a350-16e35cc8ac44.mp4

</details>

## Changelog

:cl:
add: PDA themes and the ability to set a custom theme on your PDA.
fix: Various and numerous fixes to PDA code and PDA's.
del: Tablets and tablet code, they have been replaced with PDA's
del: Computer hardware parts (Hard drives, card slots, etc)
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
I personally think we should go back to magatsuchis original tgui pda's BEFORE the  edits just changed all their shit to just be scuffed tablets

personally

**Comment by QuacksQ** [comment]
Closing this untill I'm back next week

**Comment by QuacksQ** [comment]
No more merge conflict 🥳

**Comment by QuacksQ** [comment]
The merge conflict label is a lie its not real

**Review by RimiNosha — APPROVED** [review]
Looks good to me, any new issues can be fixed as need be, though I doubt there'll be many, if any at all.

**Comment by nevimer** [comment]
Failing in prettier.

**Comment by QuacksQ** [comment]
> Failing in prettier.

Failing in what?

**Comment by nevimer** [comment]
Weird, it is failing locally for me, but not in CI

**Pull request merged**
