### PR TITLE
[FEEDBACK WANTED] Swaps Out The TGUI Default Theme

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

Default TGUI and NTOS theme is ew. Let's make it more thematically appropriate for the server!

## How Does This Help ***Gameplay***?

Makes those corners sharp enough to kill someone, as the creator intended.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary> 

image
image
image
image
image
image
image

</details>

## Changelog

:cl:
qol: The TGUI theme now looks far more distinct, and a little more unique to us!
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Needs more feedback, potentially test merge for friday.

**Comment by QuacksQ** [comment]
image

Selected options don't highlight in this UI anymore.

**Comment by QuacksQ** [comment]
image

D-pad on RPD UI is funky

**Comment by QuacksQ** [comment]
image

image

This needs to be spaced apart further

**Comment by QuacksQ** [comment]
image

Gas filter UI window needs to be made slightly larger so theres no need to scroll

**Comment by QuacksQ** [comment]
image

image

Colors of the text and background result in unreadable target input on smes

**Comment by QuacksQ** [comment]
image

Cargo order screen has some weird stuff going on, on the left. Maybe push the list of crate categories and search bar to the right by a few pixels so the orange bar doesn't get cut off anymore.

**Comment by QuacksQ** [comment]
image

Disposals UI window needs to be made slightly larger, currently you can scroll on it while its not really needed.

**Comment by QuacksQ** [comment]
image

Not sure if these also needed to have their edges straightened

**Comment by QuacksQ** [comment]
image

Random blue lines and UI bits in research UI. (Expiriment UI also has this)

**Comment by RimiNosha** [comment]
UI appears to display properly on everything now. Should be good for a merge.

**Comment by RimiNosha** [comment]
All noted issues with the UI since last playtest was fixed. Fullmerging now due to potential future conflicts.

**Pull request merged**
