### PR TITLE
[PORT] [Help Wanted] WIP Grid Inventory from MS13

### PR DESCRIPTION
**Pull request by QuacksQ**
## About The Pull Request
Ports the Grid Inventory from MS13
- https://github.com/Mojave-Sun/mojave-sun-13/pull/2022

This is still a WIP because I'm banging rocks together over here.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary> 
Soon ™️ 
</details>

## Changelog
:cl:
add: Changes the Inventory system to the Grid inventory from MS13
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
Oh wow what a cool feature I wonder who coded it

**Comment by RimiNosha** [comment]
:)

**Comment by QuacksQ** [comment]
7h368t

**Comment by ChungusGamer666** [comment]
Contact me on Discord of you want to revive this, I can try to provide help in my free time.

**Pull request closed without merging**
